#!/usr/bin/expect -f

spawn sdm login
set sdm_id $spawn_id
expect "e-mail:"
send "asmith@better.com\r"
expect -re ".*(https://.*)" {
    spawn xdg-open "$expect_out(1,string)"
}
interact -i $sdm_id
spawn sdm connect -a
